// Copyright 2021-2022 Axiom-Team
//
// This file is part of Duniter-v2S.
//
// Duniter-v2S is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// Duniter-v2S is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Duniter-v2S. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sonic`, CPU: `Intel Core Processor (Broadwell, no TSX, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/duniter
// benchmark
// pallet
// --genesis-builder=spec-genesis
// --steps=50
// --repeat=20
// --pallet=*
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/g1/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_identity`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_identity::WeightInfo for WeightInfo<T> {
	fn create_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1042`
		//  Estimated: `0`
		// Minimum execution time: 211_865_000 picoseconds.
		Weight::from_parts(240_966_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn confirm_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `784`
		//  Estimated: `0`
		// Minimum execution time: 101_966_000 picoseconds.
		Weight::from_parts(134_662_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn change_owner_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1009`
		//  Estimated: `0`
		// Minimum execution time: 240_627_000 picoseconds.
		Weight::from_parts(278_320_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn revoke_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `740`
		//  Estimated: `0`
		// Minimum execution time: 224_204_000 picoseconds.
		Weight::from_parts(251_334_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `i` is `[2, 1000]`.
	fn prune_item_identities_names(i: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_583_000 picoseconds.
		Weight::from_parts(16_639_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 30_624
			.saturating_add(Weight::from_parts(5_095_991, 0).saturating_mul(i.into()))
	}
	fn fix_sufficients() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `104`
		//  Estimated: `0`
		// Minimum execution time: 26_076_000 picoseconds.
		Weight::from_parts(27_553_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn link_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379`
		//  Estimated: `0`
		// Minimum execution time: 184_303_000 picoseconds.
		Weight::from_parts(208_207_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 561_000 picoseconds.
		Weight::from_parts(878_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_revoke_identity_noop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `0`
		// Minimum execution time: 17_657_000 picoseconds.
		Weight::from_parts(20_293_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_revoke_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1845`
		//  Estimated: `0`
		// Minimum execution time: 385_701_000 picoseconds.
		Weight::from_parts(509_024_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_remove_identity_noop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `0`
		// Minimum execution time: 17_772_000 picoseconds.
		Weight::from_parts(31_848_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_remove_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2294`
		//  Estimated: `0`
		// Minimum execution time: 442_295_000 picoseconds.
		Weight::from_parts(486_332_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_remove_identity_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2287`
		//  Estimated: `0`
		// Minimum execution time: 444_330_000 picoseconds.
		Weight::from_parts(665_935_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn membership_removed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `407`
		//  Estimated: `0`
		// Minimum execution time: 48_116_000 picoseconds.
		Weight::from_parts(81_320_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn prune_identities_noop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `0`
		// Minimum execution time: 10_274_000 picoseconds.
		Weight::from_parts(20_050_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn prune_identities_none() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `325`
		//  Estimated: `0`
		// Minimum execution time: 24_538_000 picoseconds.
		Weight::from_parts(41_447_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn prune_identities_err() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `914`
		//  Estimated: `0`
		// Minimum execution time: 106_990_000 picoseconds.
		Weight::from_parts(187_985_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn revoke_identity_legacy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `886`
		//  Estimated: `0`
		// Minimum execution time: 217_055_000 picoseconds.
		Weight::from_parts(357_074_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
