// Copyright 2021-2022 Axiom-Team
//
// This file is part of Duniter-v2S.
//
// Duniter-v2S is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// Duniter-v2S is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Duniter-v2S. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_preimage`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sonic`, CPU: `Intel Core Processor (Broadwell, no TSX, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/duniter
// benchmark
// pallet
// --genesis-builder=spec-genesis
// --steps=50
// --repeat=20
// --pallet=*
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/g1/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_preimage`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_preimage::WeightInfo for WeightInfo<T> {
	/// The range of component `s` is `[0, 4194304]`.
	fn note_preimage(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `0`
		// Minimum execution time: 39_360_000 picoseconds.
		Weight::from_parts(219_521_347, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 24
			.saturating_add(Weight::from_parts(3_250, 0).saturating_mul(s.into()))
	}
	/// The range of component `s` is `[0, 4194304]`.
	fn note_requested_preimage(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 54_447_000 picoseconds.
		Weight::from_parts(359_410_017, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 22
			.saturating_add(Weight::from_parts(3_189, 0).saturating_mul(s.into()))
	}
	/// The range of component `s` is `[0, 4194304]`.
	fn note_no_deposit_preimage(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 43_107_000 picoseconds.
		Weight::from_parts(230_154_715, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 27
			.saturating_add(Weight::from_parts(3_237, 0).saturating_mul(s.into()))
	}
	fn unnote_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `0`
		// Minimum execution time: 79_585_000 picoseconds.
		Weight::from_parts(100_423_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unnote_no_deposit_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `106`
		//  Estimated: `0`
		// Minimum execution time: 81_060_000 picoseconds.
		Weight::from_parts(125_550_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `0`
		// Minimum execution time: 68_606_000 picoseconds.
		Weight::from_parts(93_121_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_no_deposit_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `106`
		//  Estimated: `0`
		// Minimum execution time: 51_579_000 picoseconds.
		Weight::from_parts(71_643_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_unnoted_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `0`
		// Minimum execution time: 47_025_000 picoseconds.
		Weight::from_parts(61_129_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_requested_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 30_883_000 picoseconds.
		Weight::from_parts(38_120_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unrequest_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `106`
		//  Estimated: `0`
		// Minimum execution time: 72_370_000 picoseconds.
		Weight::from_parts(77_970_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unrequest_unnoted_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 31_120_000 picoseconds.
		Weight::from_parts(33_045_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unrequest_multi_referenced_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 32_097_000 picoseconds.
		Weight::from_parts(33_949_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[1, 1024]`.
	fn ensure_updated(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (179 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 55_310_000 picoseconds.
		Weight::from_parts(55_957_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 243_424
			.saturating_add(Weight::from_parts(63_534_774, 0).saturating_mul(n.into()))
	}
}
