// Copyright 2021-2022 Axiom-Team
//
// This file is part of Duniter-v2S.
//
// Duniter-v2S is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// Duniter-v2S is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Duniter-v2S. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sonic`, CPU: `Intel Core Processor (Broadwell, no TSX, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/duniter
// benchmark
// pallet
// --genesis-builder=spec-genesis
// --steps=50
// --repeat=20
// --pallet=*
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/gdev/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_identity`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_identity::WeightInfo for WeightInfo<T> {
	fn create_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1157`
		//  Estimated: `0`
		// Minimum execution time: 235_154_000 picoseconds.
		Weight::from_parts(245_556_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn confirm_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `784`
		//  Estimated: `0`
		// Minimum execution time: 104_727_000 picoseconds.
		Weight::from_parts(109_017_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn change_owner_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1037`
		//  Estimated: `0`
		// Minimum execution time: 270_524_000 picoseconds.
		Weight::from_parts(312_160_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn revoke_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `740`
		//  Estimated: `0`
		// Minimum execution time: 250_735_000 picoseconds.
		Weight::from_parts(283_822_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `i` is `[2, 1000]`.
	fn prune_item_identities_names(i: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 17_147_000 picoseconds.
		Weight::from_parts(20_349_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 17_000
			.saturating_add(Weight::from_parts(4_727_902, 0).saturating_mul(i.into()))
	}
	fn fix_sufficients() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `104`
		//  Estimated: `0`
		// Minimum execution time: 24_369_000 picoseconds.
		Weight::from_parts(28_753_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn link_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379`
		//  Estimated: `0`
		// Minimum execution time: 153_271_000 picoseconds.
		Weight::from_parts(170_729_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 434_000 picoseconds.
		Weight::from_parts(527_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_revoke_identity_noop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `0`
		// Minimum execution time: 15_589_000 picoseconds.
		Weight::from_parts(17_320_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_revoke_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1846`
		//  Estimated: `0`
		// Minimum execution time: 352_361_000 picoseconds.
		Weight::from_parts(650_214_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_remove_identity_noop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `327`
		//  Estimated: `0`
		// Minimum execution time: 17_378_000 picoseconds.
		Weight::from_parts(29_388_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_remove_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2409`
		//  Estimated: `0`
		// Minimum execution time: 482_038_000 picoseconds.
		Weight::from_parts(550_302_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_remove_identity_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2402`
		//  Estimated: `0`
		// Minimum execution time: 472_745_000 picoseconds.
		Weight::from_parts(591_310_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn membership_removed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `407`
		//  Estimated: `0`
		// Minimum execution time: 49_015_000 picoseconds.
		Weight::from_parts(52_480_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn prune_identities_noop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `0`
		// Minimum execution time: 10_445_000 picoseconds.
		Weight::from_parts(10_716_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn prune_identities_none() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `325`
		//  Estimated: `0`
		// Minimum execution time: 25_347_000 picoseconds.
		Weight::from_parts(26_705_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn prune_identities_err() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `915`
		//  Estimated: `0`
		// Minimum execution time: 112_083_000 picoseconds.
		Weight::from_parts(117_826_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn revoke_identity_legacy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `886`
		//  Estimated: `0`
		// Minimum execution time: 232_624_000 picoseconds.
		Weight::from_parts(236_169_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
