query GetChangesQuery($milestone: String!) {
  project(fullPath: "nodes/rust/duniter-v2s") {
		mergeRequests(milestoneTitle: $milestone, state: merged) {
      nodes {
        iid
        title
      }
    }
  }
}
