[package]
authors.workspace = true
description = "duniter test parameters macro"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pallet-duniter-test-parameters-macro"
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true, default-features = false }
quote = { workspace = true, default-features = false }
syn = { workspace = true, features = ["extra-traits", "fold", "full", "visit"] }
