# Copied from SDK e2f5d44770e741d708b5ee551cf152afccee0b54.
# See ../README.md for the manifest changes and removal conditions.
[package]
name = "sp-tracing"
version = "19.0.0"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://paritytech.github.io/polkadot-sdk/"
repository = "https://github.com/paritytech/polkadot-sdk.git"
description = "Instrumentation primitives and macros for Substrate."
readme = "README.md"


[package.metadata.docs.rs]
# let's default to wasm32
default-target = "wasm32-unknown-unknown"
# with the tracing enabled
features = ["with-tracing"]
# allowing for linux-gnu here, too, allows for `std` to show up as well
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]

[dependencies]
codec = { version = "3.7.5", default-features = false, package = "parity-scale-codec", features = ["derive"] }
regex = { version = "1.10.2", optional = true }
tracing = { version = "0.1.37", default-features = false }
tracing-core = { version = "0.1.32", default-features = false }
tracing-subscriber = { version = "=0.3.20", optional = true, features = ["env-filter", "time", "tracing-log"] }

[features]
default = ["std"]
with-tracing = ["codec/derive", "codec/full"]
std = [
	"codec/std",
	"regex",
	"tracing-core/std",
	"tracing-subscriber",
	"tracing/std",
	"with-tracing",
]

[lints.rust]
suspicious_double_ref_op = { level = "allow", priority = 2 }
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(build_opt_level, values(\"3\"))", "cfg(build_profile, values(\"debug\", \"release\"))", "cfg(enable_alloc_error_handler)", "cfg(fuzzing)", "cfg(ignore_flaky_test)", "cfg(substrate_runtime)"] }

[lints.clippy]
all = { level = "allow", priority = 0 }
bind_instead_of_map = { level = "allow", priority = 2 }
borrowed-box = { level = "allow", priority = 2 }
complexity = { level = "warn", priority = 1 }
correctness = { level = "warn", priority = 1 }
default_constructed_unit_structs = { level = "allow", priority = 2 }
derivable_impls = { level = "allow", priority = 2 }
eq_op = { level = "allow", priority = 2 }
erasing_op = { level = "allow", priority = 2 }
extra-unused-type-parameters = { level = "allow", priority = 2 }
identity-op = { level = "allow", priority = 2 }
if-same-then-else = { level = "allow", priority = 2 }
needless-lifetimes = { level = "allow", priority = 2 }
needless_option_as_deref = { level = "allow", priority = 2 }
nonminimal-bool = { level = "allow", priority = 2 }
option-map-unit-fn = { level = "allow", priority = 2 }
stable_sort_primitive = { level = "allow", priority = 2 }
too-many-arguments = { level = "allow", priority = 2 }
type_complexity = { level = "allow", priority = 2 }
unit_arg = { level = "allow", priority = 2 }
unnecessary_cast = { level = "allow", priority = 2 }
useless_conversion = { level = "allow", priority = 2 }
while_immutable_condition = { level = "allow", priority = 2 }
zero-prefixed-literal = { level = "allow", priority = 2 }
