// Copyright 2021 Axiom-Team
//
// This file is part of Duniter-v2S.
//
// Duniter-v2S is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// Duniter-v2S is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Duniter-v2S. If not, see <https://www.gnu.org/licenses/>.

#![cfg(feature = "constant-fees")]

mod common;

use codec::Encode;
use common::*;
use frame_support::{assert_ok, traits::StoredMap};
use gtest_runtime::*;
use pallet_identity::IdtyStatus;
use sp_core::Pair;
use sp_keyring::sr25519::Keyring;
use sp_runtime::MultiAddress;

#[test]
fn test_local_genesis_authority_never_expires() {
    ExtBuilder::new(1, 3, 4).build().execute_with(|| {
        assert_eq!(
            Membership::membership(1)
                .expect("authority membership should exist")
                .expire_on,
            NON_EXPIRING_LOCAL_AUTHORITY
        );
        assert!(
            Certification::certs_by_receiver(1)
                .iter()
                .all(|(_, expire_on)| *expire_on == NON_EXPIRING_LOCAL_AUTHORITY)
        );

        let target_block = MembershipPeriod::get().max(ValidityPeriod::get()) + 5;
        run_to_block(target_block);

        assert_eq!(
            Identity::identity(1)
                .expect("authority identity should exist")
                .status,
            IdtyStatus::Member
        );
        assert_eq!(
            Membership::membership(1)
                .expect("authority membership should still exist")
                .expire_on,
            NON_EXPIRING_LOCAL_AUTHORITY
        );
        assert!(
            Certification::certs_by_receiver(1)
                .iter()
                .all(|(_, expire_on)| *expire_on == NON_EXPIRING_LOCAL_AUTHORITY)
        );
    })
}

#[test]
fn test_change_owner_key_with_batch_all_claim_transfer_all() {
    ExtBuilder::new(1, 3, 4)
        .with_initial_balances(vec![(Keyring::Dave.to_account_id(), 1_000)])
        .build()
        .execute_with(|| {
            run_to_block(4);

            let genesis_hash = System::block_hash(0);
            let dave = Keyring::Dave.to_account_id();
            let ferdie = Keyring::Ferdie.to_account_id();
            let dave_initial_balance = Balances::free_balance(dave.clone());
            let payload = (b"icok", genesis_hash, 4u32, dave.clone()).encode();
            let signature = Keyring::Ferdie.sign(&payload);

            assert_eq!(Identity::identity_index_of(&dave), Some(4));
            assert_eq!(Identity::identity_index_of(&ferdie), None);
            assert_eq!(Balances::free_balance(ferdie.clone()), 0);

            let batch_call = RuntimeCall::Utility(pallet_utility::Call::batch_all {
                calls: vec![
                    RuntimeCall::UniversalDividend(pallet_universal_dividend::Call::claim_uds {}),
                    RuntimeCall::Balances(pallet_balances::Call::transfer_all {
                        dest: MultiAddress::Id(ferdie.clone()),
                        keep_alive: false,
                    }),
                    RuntimeCall::Identity(pallet_identity::Call::change_owner_key {
                        new_key: ferdie.clone(),
                        new_key_sig: signature.into(),
                    }),
                ],
            });
            let batch_xt = get_unchecked_extrinsic(batch_call, Keyring::Dave, 0u64, 0);
            assert_ok!(Executive::apply_extrinsic(batch_xt));

            assert_eq!(Identity::identity_index_of(&dave), None);
            assert_eq!(Identity::identity_index_of(&ferdie), Some(4));
            assert_eq!(
                frame_system::Pallet::<Runtime>::get(&ferdie).linked_idty,
                Some(4)
            );
            assert_eq!(Balances::free_balance(dave.clone()), 0);
            assert!(Balances::free_balance(ferdie.clone()) >= dave_initial_balance);

            // Refund generated by the batch extrinsic itself must target the new owner key.
            let queued_refund = pallet_quota::RefundQueue::<Runtime>::get()
                .iter()
                .find(|refund| refund.identity == 4u32)
                .cloned()
                .expect("batch extrinsic should have queued a refund");
            assert_eq!(queued_refund.account, ferdie.clone());
            assert!(queued_refund.amount > 0);
            let ferdie_balance_before_refund = Balances::free_balance(ferdie.clone());

            // Advance one block to execute quota on_idle processing.
            let block_after_refund = System::block_number() + 1;
            run_to_block(block_after_refund);

            assert!(pallet_quota::RefundQueue::<Runtime>::get().is_empty());
            let refunded_amount = System::events()
                .iter()
                .find_map(|event_record| match &event_record.event {
                    RuntimeEvent::Quota(pallet_quota::Event::Refunded {
                        who,
                        identity,
                        amount,
                    }) if who == &ferdie && *identity == 4u32 => Some(*amount),
                    _ => None,
                })
                .expect("quota refund should be emitted for the new key");
            assert!(refunded_amount > 0);
            assert_eq!(
                Balances::free_balance(ferdie.clone()),
                ferdie_balance_before_refund + refunded_amount
            );
            assert!(!System::events().iter().any(|event_record| {
                matches!(
                    &event_record.event,
                    RuntimeEvent::Quota(pallet_quota::Event::Refunded { who, .. })
                    if who == &dave
                )
            }));

            // Keep advancing blocks with on_idle enabled in the harness.
            run_to_block(block_after_refund + 1);
        })
}

#[test]
fn test_change_owner_key_reaps_old_old_owner_key_without_balance() {
    ExtBuilder::new(1, 3, 5)
        .with_initial_balances(vec![
            (Keyring::Ferdie.to_account_id(), 1_000),
            (
                get_account_id_from_seed::<sp_core::sr25519::Public>("Zoe"),
                1_000,
            ),
        ])
        .build()
        .execute_with(|| {
            run_to_block(4);

            let genesis_hash = System::block_hash(0);
            let dave = Keyring::Dave.to_account_id();
            let ferdie = Keyring::Ferdie.to_account_id();
            let zoe = get_account_id_from_seed::<sp_core::sr25519::Public>("Zoe");
            let zoe_signer = sp_core::sr25519::Pair::from_string("//Zoe", None)
                .expect("static test key should be valid");

            assert_eq!(Balances::free_balance(dave.clone()), 0);
            assert_eq!(
                frame_system::Pallet::<Runtime>::get(&dave).linked_idty,
                Some(4)
            );

            let first_payload = (b"icok", genesis_hash, 4u32, dave.clone()).encode();
            let first_signature = Keyring::Ferdie.sign(&first_payload);
            assert_ok!(Identity::change_owner_key(
                RuntimeOrigin::signed(dave.clone()),
                ferdie.clone(),
                first_signature.into()
            ));

            assert_eq!(Identity::identity_index_of(&dave), None);
            assert_eq!(Identity::identity_index_of(&ferdie), Some(4));
            assert_eq!(
                frame_system::Pallet::<Runtime>::get(&dave).linked_idty,
                Some(4)
            );

            System::set_block_number(System::block_number() + ChangeOwnerKeyPeriod::get());

            let second_payload = (b"icok", genesis_hash, 4u32, ferdie.clone()).encode();
            let second_signature = zoe_signer.sign(&second_payload);
            assert_ok!(Identity::change_owner_key(
                RuntimeOrigin::signed(ferdie.clone()),
                zoe.clone(),
                second_signature.into()
            ));

            assert_eq!(Identity::identity_index_of(&zoe), Some(4));
            assert_eq!(
                frame_system::Pallet::<Runtime>::get(&dave),
                pallet_duniter_account::AccountData::default()
            );
            assert_eq!(Balances::free_balance(dave), 0);
        })
}
