//! Machine-readable metadata for the daemon options shared with the node.

use anyhow::{Context, Result, bail};
use clap::{ArgAction, CommandFactory};
use serde_json::{Value, json};
use std::{collections::BTreeSet, path::PathBuf};

pub fn schema(mut command: clap::Command) -> Result<Value> {
    command.build();
    let mut options = Vec::new();
    let mut env_names = BTreeSet::new();
    for arg in command.get_arguments() {
        let Some(long) = arg.get_long() else { continue };
        let action = match arg.get_action() {
            ArgAction::Set => "set",
            ArgAction::Append => "append",
            ArgAction::SetTrue => "set_true",
            ArgAction::SetFalse => "set_false",
            ArgAction::Count => "count",
            ArgAction::Help | ArgAction::HelpShort | ArgAction::HelpLong | ArgAction::Version => {
                continue;
            }
            other => bail!("unsupported Clap action for --{long}: {other:?}"),
        };
        let env = format!("DUNITER_{}", long.replace('-', "_").to_ascii_uppercase());
        if !env_names.insert(env.clone()) {
            bail!("duplicate generated environment variable: {env}");
        }
        let arity = arg.get_num_args().context("built argument has no arity")?;
        options.push(json!({
            "id": arg.get_id().as_str(),
            "flag": long,
            "env": env,
            "action": action,
            "min_values": arity.min_values(),
            "max_values": (arity.max_values() != usize::MAX).then_some(arity.max_values()),
            "value_delimiter": arg.get_value_delimiter().map(|v| v.to_string()),
            "require_equals": arg.is_require_equals_set(),
            "allow_hyphen_values": arg.is_allow_hyphen_values_set(),
            "default_values": arg.get_default_values().iter().map(|v| v.to_str().context("non-UTF-8 default")).collect::<Result<Vec<_>>>()?,
            "possible_values": arg.get_possible_values().iter().map(|v| v.get_name()).collect::<Vec<_>>(),
            "conflicts": command.get_arg_conflicts_with(arg).iter().map(|v| v.get_id().as_str()).collect::<Vec<_>>(),
            "help": arg.get_help().map(ToString::to_string),
            "hidden": arg.is_hide_set(),
        }));
    }
    options.sort_by(|a, b| a["flag"].as_str().cmp(&b["flag"].as_str()));
    Ok(json!({"schema_version": 1, "command": "duniter", "scope": "daemon", "options": options}))
}

pub fn export(output: Option<PathBuf>, check: bool) -> Result<()> {
    let value = schema(duniter_cli::RunOptions::command())?;
    let mut bytes = serde_json::to_vec_pretty(&value)?;
    bytes.push(b'\n');
    let output_is_default = output.is_none();
    let path = output.unwrap_or_else(|| {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../node/cli/schema.json")
    });
    if check {
        let current = std::fs::read(&path).with_context(|| format!("read {}", path.display()))?;
        if current != bytes {
            bail!(
                "CLI catalogue is stale; run cargo xtask export-cli-schema and commit node/cli/schema.json"
            );
        }
    } else {
        std::fs::write(&path, bytes).with_context(|| format!("write {}", path.display()))?;
    }
    if output_is_default {
        let path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../docker/duniter-cli-options.sh");
        let mut command = duniter_cli::RunOptions::command();
        command.build();
        let mut shell = String::from(
            "# Generated by cargo xtask export-cli-schema. Do not edit.\nduniter_env_configure() {\n",
        );
        for option in value["options"].as_array().unwrap() {
            let flag = option["flag"].as_str().unwrap();
            let arg = command
                .get_arguments()
                .find(|arg| arg.get_long() == Some(flag))
                .unwrap();
            let short = arg.get_short().map(|c| c.to_string()).unwrap_or_default();
            shell.push_str(&format!(
                "  duniter_env_option '{}' '{}' '{}' '{}' || return\n",
                option["env"].as_str().unwrap(),
                flag,
                option["action"].as_str().unwrap(),
                short
            ));
        }
        shell.push_str("}\n");
        if check {
            if std::fs::read_to_string(&path)? != shell {
                bail!("Docker CLI mappings are stale; run cargo xtask export-cli-schema");
            }
        } else {
            std::fs::write(path, shell)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reflects_actions_arity_defaults_and_conflicts() {
        let command = clap::Command::new("test")
            .arg(
                clap::Arg::new("blocks")
                    .long("blocks-pruning")
                    .default_value("256"),
            )
            .arg(
                clap::Arg::new("enable")
                    .long("enable")
                    .action(ArgAction::SetTrue)
                    .conflicts_with("blocks"),
            )
            .arg(
                clap::Arg::new("peers")
                    .long("peers")
                    .num_args(1..)
                    .action(ArgAction::Append),
            );
        let value = schema(command).unwrap();
        let options = value["options"].as_array().unwrap();
        assert_eq!(options[0]["env"], "DUNITER_BLOCKS_PRUNING");
        assert_eq!(options[0]["default_values"], json!(["256"]));
        assert_eq!(options[1]["action"], "set_true");
        assert_eq!(options[1]["max_values"], 0);
        assert_eq!(options[1]["conflicts"], json!(["blocks"]));
        assert_eq!(options[2]["action"], "append");
        assert!(options[2]["max_values"].is_null());
    }

    #[test]
    fn actual_daemon_includes_substrate_and_duniter_options() {
        let value = schema(duniter_cli::RunOptions::command()).unwrap();
        let options = value["options"].as_array().unwrap();
        for flag in [
            "blocks-pruning",
            "state-pruning",
            "indexer-batch-sink-url",
            "sealing",
        ] {
            assert!(options.iter().any(|o| o["flag"] == flag), "missing {flag}");
        }
        assert_eq!(
            options
                .iter()
                .find(|o| o["flag"] == "trie-cache-size")
                .unwrap()["default_values"],
            json!(["536870912"])
        );
        assert_eq!(value, schema(duniter_cli::RunOptions::command()).unwrap());
    }
}
