// Copyright 2021-2022 Axiom-Team
//
// This file is part of Duniter-v2S.
//
// Duniter-v2S is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// Duniter-v2S is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Duniter-v2S. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_distance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sonic`, CPU: `Intel Core Processor (Broadwell, no TSX, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/duniter
// benchmark
// pallet
// --genesis-builder=spec-genesis
// --steps=50
// --repeat=20
// --pallet=*
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/gtest/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_distance`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_distance::WeightInfo for WeightInfo<T> {
	fn request_distance_evaluation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1134`
		//  Estimated: `0`
		// Minimum execution time: 195_546_000 picoseconds.
		Weight::from_parts(207_740_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_distance_evaluation_for() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1163`
		//  Estimated: `0`
		// Minimum execution time: 203_410_000 picoseconds.
		Weight::from_parts(226_281_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `i` is `[1, 1300]`.
	fn update_evaluation(i: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303 + i * (10 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 46_161_000 picoseconds.
		Weight::from_parts(41_705_240, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 9_343
			.saturating_add(Weight::from_parts(524_213, 0).saturating_mul(i.into()))
	}
	/// The range of component `i` is `[1, 1300]`.
	fn force_update_evaluation(i: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `162 + i * (10 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 35_128_000 picoseconds.
		Weight::from_parts(38_672_673, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 7_964
			.saturating_add(Weight::from_parts(496_730, 0).saturating_mul(i.into()))
	}
	fn force_valid_distance_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `539`
		//  Estimated: `0`
		// Minimum execution time: 93_982_000 picoseconds.
		Weight::from_parts(129_635_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_initialize_overhead() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 578_000 picoseconds.
		Weight::from_parts(667_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_evaluation_success() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `951`
		//  Estimated: `0`
		// Minimum execution time: 194_496_000 picoseconds.
		Weight::from_parts(212_820_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_evaluation_failure() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `475`
		//  Estimated: `0`
		// Minimum execution time: 140_420_000 picoseconds.
		Weight::from_parts(165_015_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn do_evaluation_overhead() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `136`
		//  Estimated: `0`
		// Minimum execution time: 14_943_000 picoseconds.
		Weight::from_parts(15_459_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `0`
		// Minimum execution time: 12_477_000 picoseconds.
		Weight::from_parts(13_187_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
