// Copyright 2021-2022 Axiom-Team
//
// This file is part of Duniter-v2S.
//
// Duniter-v2S is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// Duniter-v2S is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Duniter-v2S. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_preimage`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sonic`, CPU: `Intel Core Processor (Broadwell, no TSX, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/duniter
// benchmark
// pallet
// --genesis-builder=spec-genesis
// --steps=50
// --repeat=20
// --pallet=*
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/gtest/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_preimage`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_preimage::WeightInfo for WeightInfo<T> {
	/// The range of component `s` is `[0, 4194304]`.
	fn note_preimage(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `0`
		// Minimum execution time: 40_086_000 picoseconds.
		Weight::from_parts(325_146_686, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 21
			.saturating_add(Weight::from_parts(3_001, 0).saturating_mul(s.into()))
	}
	/// The range of component `s` is `[0, 4194304]`.
	fn note_requested_preimage(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 46_773_000 picoseconds.
		Weight::from_parts(47_795_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 14
			.saturating_add(Weight::from_parts(3_257, 0).saturating_mul(s.into()))
	}
	/// The range of component `s` is `[0, 4194304]`.
	fn note_no_deposit_preimage(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 53_207_000 picoseconds.
		Weight::from_parts(230_620_307, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 23
			.saturating_add(Weight::from_parts(3_124, 0).saturating_mul(s.into()))
	}
	fn unnote_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `0`
		// Minimum execution time: 79_802_000 picoseconds.
		Weight::from_parts(125_646_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unnote_no_deposit_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `106`
		//  Estimated: `0`
		// Minimum execution time: 84_939_000 picoseconds.
		Weight::from_parts(92_860_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `0`
		// Minimum execution time: 70_302_000 picoseconds.
		Weight::from_parts(83_447_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_no_deposit_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `106`
		//  Estimated: `0`
		// Minimum execution time: 51_540_000 picoseconds.
		Weight::from_parts(61_609_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_unnoted_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `0`
		// Minimum execution time: 59_281_000 picoseconds.
		Weight::from_parts(62_320_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn request_requested_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 29_968_000 picoseconds.
		Weight::from_parts(34_540_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unrequest_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `106`
		//  Estimated: `0`
		// Minimum execution time: 78_723_000 picoseconds.
		Weight::from_parts(117_066_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unrequest_unnoted_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 31_084_000 picoseconds.
		Weight::from_parts(38_286_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unrequest_multi_referenced_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `68`
		//  Estimated: `0`
		// Minimum execution time: 33_503_000 picoseconds.
		Weight::from_parts(56_361_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[1, 1024]`.
	fn ensure_updated(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (179 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 63_687_000 picoseconds.
		Weight::from_parts(64_855_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 287_547
			.saturating_add(Weight::from_parts(63_102_255, 0).saturating_mul(n.into()))
	}
}
