// Copyright 2021-2022 Axiom-Team
//
// This file is part of Duniter-v2S.
//
// Duniter-v2S is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// Duniter-v2S is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Duniter-v2S. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_authority_members`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sonic`, CPU: `Intel Core Processor (Broadwell, no TSX, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/duniter
// benchmark
// pallet
// --genesis-builder=spec-genesis
// --steps=50
// --repeat=20
// --pallet=*
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/gtest/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_authority_members`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_authority_members::WeightInfo for WeightInfo<T> {
	fn go_offline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `868`
		//  Estimated: `0`
		// Minimum execution time: 91_980_000 picoseconds.
		Weight::from_parts(114_562_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn go_online() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1324`
		//  Estimated: `0`
		// Minimum execution time: 106_820_000 picoseconds.
		Weight::from_parts(160_642_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_session_keys() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1773`
		//  Estimated: `0`
		// Minimum execution time: 128_740_000 picoseconds.
		Weight::from_parts(142_074_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn remove_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `847`
		//  Estimated: `0`
		// Minimum execution time: 232_036_000 picoseconds.
		Weight::from_parts(273_600_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn remove_member_from_blacklist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `199`
		//  Estimated: `0`
		// Minimum execution time: 32_353_000 picoseconds.
		Weight::from_parts(55_738_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
