[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "gdev-runtime"
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["std"]
constant-fees = ["common-runtime/constant-fees"]
runtime-benchmarks = [
	"common-runtime/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-authority-members/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-certification/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-distance/runtime-benchmarks",
	"pallet-duniter-account/runtime-benchmarks",
	"pallet-duniter-test-parameters/runtime-benchmarks",
	"pallet-duniter-wot/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-oneshot-account/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-provide-randomness/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-quota/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-session-benchmarking/runtime-benchmarks",
	"pallet-smith-members/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-universal-dividend/runtime-benchmarks",
	"pallet-upgrade-origin/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
std = [
	"codec/std",
	"common-runtime/std",
	"frame-benchmarking?/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-benchmarking/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"log/std",
	"node-primitives/std",
	"pallet-atomic-swap/std",
	"pallet-authority-discovery/std",
	"pallet-authority-members/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-certification/std",
	"pallet-collective/std",
	"pallet-distance/std",
	"pallet-duniter-account/std",
	"pallet-duniter-test-parameters/std",
	"pallet-duniter-wot/std",
	"pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-offences/std",
	"pallet-oneshot-account/std",
	"pallet-preimage/std",
	"pallet-provide-randomness/std",
	"pallet-proxy/std",
	"pallet-quota/std",
	"pallet-scheduler/std",
	"pallet-session-benchmarking/std",
	"pallet-session/std",
	"pallet-smith-members/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"pallet-universal-dividend/std",
	"pallet-upgrade-origin/std",
	"pallet-utility/std",
	"scale-info/std",
	"serde/std",
	"serde_derive",
	"sp-api/std",
	"sp-arithmetic/std",
	"sp-authority-discovery/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-distance/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-membership/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
]
try-runtime = [
	"common-runtime/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-atomic-swap/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authority-members/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-certification/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-distance/try-runtime",
	"pallet-duniter-account/try-runtime",
	"pallet-duniter-test-parameters/try-runtime",
	"pallet-duniter-wot/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-oneshot-account/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-provide-randomness/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-quota/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-session-benchmarking/try-runtime",
	"pallet-session/try-runtime",
	"pallet-smith-members/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-universal-dividend/try-runtime",
	"pallet-upgrade-origin/try-runtime",
	"pallet-utility/try-runtime",
	"sp-distance/try-runtime",
	"sp-membership/try-runtime",
	"sp-runtime/try-runtime",
]

[dev-dependencies]
sp-io = { workspace = true }
sp-keyring = { workspace = true }
sp-staking = { workspace = true }

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[dependencies]
codec = { workspace = true, features = ["derive"] }
common-runtime = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-executive = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-system-rpc-runtime-api = { workspace = true }
hex-literal = { workspace = true, optional = true }
log = { workspace = true }
node-primitives = { workspace = true }
pallet-atomic-swap = { workspace = true }
pallet-authority-discovery = { workspace = true }
pallet-authority-members = { workspace = true }
pallet-authorship = { workspace = true }
pallet-babe = { workspace = true }
pallet-balances = { workspace = true }
pallet-certification = { workspace = true }
pallet-collective = { workspace = true }
pallet-distance = { workspace = true }
pallet-duniter-account = { workspace = true }
pallet-duniter-test-parameters = { workspace = true }
pallet-duniter-wot = { workspace = true }
pallet-grandpa = { workspace = true }
pallet-identity = { workspace = true }
pallet-im-online = { workspace = true }
pallet-membership = { workspace = true }
pallet-multisig = { workspace = true }
pallet-offences = { workspace = true }
pallet-oneshot-account = { workspace = true }
pallet-preimage = { workspace = true }
pallet-provide-randomness = { workspace = true }
pallet-proxy = { workspace = true }
pallet-quota = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-session = { workspace = true }
pallet-session-benchmarking = { workspace = true }
pallet-smith-members = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury = { workspace = true }
pallet-universal-dividend = { workspace = true }
pallet-upgrade-origin = { workspace = true }
pallet-utility = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true }
serde_derive = { workspace = true, optional = true }
sp-api = { workspace = true }
sp-arithmetic = { workspace = true }
sp-authority-discovery = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-core = { workspace = true }
sp-distance = { workspace = true }
sp-genesis-builder = { workspace = true }
sp-inherents = { workspace = true }
sp-membership = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
